---
title: "Police Violence Project"
output: html_document
---

# Introduction

Police violence stands as a compelling and vital topic with far-reaching implications for justice, equality, public safety, and community-police relations. It prompts discussions and actions aimed at reshaping the criminal justice system to be fair and accountable. This issue brings attention to systemic inequalities, emphasizing the need for transparency and accountability within law enforcement. It contributes to public safety by creating awareness of potential risks and rebuilding trust between communities and the police. Furthermore, police violence serves as a catalyst for policy reforms, legislative changes, and community engagement, fostering a collective effort to address systemic issues such as racism and inequality. The media's role in shaping public awareness and the international perspective on this issue further amplify its significance, emphasizing the global nature of the challenge and the shared responsibility to seek equitable solutions. In essence, police violence acts as a linchpin for comprehensive discussions and actions, driving societies toward a more just, accountable, and community-oriented approach to law enforcement.

The topic of police violence has been extensively covered in the media and academic literature. There have been multiple stories on excessive use of police power, racial inequalities, racism, and the push for systematic change in law enforcement. An example of police violence coming to uproar in media is the Black Lives Matter movement. "Black Lives Matter (BLM) is a decentralized political and social movement that seeks to highlight racism, discrimination, and racial inequality experienced by black people, and promote anti-racism. Its primary concerns are incidents of [**police brutality**]{.underline} and racially motivated violence against black people." We already know that there are crimes happening around the world but we wanted to provide information for people about what areas have potential danger to keep them aware of what goes on around their city. This is interesting because we can see the types of reasons for police violence in the world, why people do it , etc. Something I want to add to what already exists is answers to the causes of police violence in the United States.

With multiple knowledge on what we already know on police violence in the US. We want to highlight why we are doing this. Some question we would like to answer based off of the data is...

-   **Question 1: What are the root causes of police violence?**

-   Why do some people die due to police violence when they were either unarmed or did not threaten them at all? What are the main causes of police violence? What trends can we find among police violence and its association to mental illness or population density.

-   **Question 2: How effective are current accountability mechanisms, including body-worn cameras and internal investigations?**

    -   We would like to investigate if body cam footage keep police officers accountable or if they dont

-   **Question 3: Where is police violence more prevalent?**

    -   We want to explore where police violence is more commonly located. With this we can have a general idea of why it is more prevalent in these areas and can open more questions on

## Why should someone care about our report?

-   **250,000 - An estimated 250,000 civilian injuries are caused by law enforcement officers annually.**

-   **600 - More than 600 people are killed by law enforcement in the U.S. each year.**

These are some facts from the "Law Enforcement Epidemiology Project" from the University of Illinois.

This is interesting because being able to see the correlation with certain things/topic that lead to police violence is crucial information to keep people informed on the law enforcement and the causes of violence in our communities

People should care about this report since police violence is a on going problem in the United States. Being able to have the right to life, security, and freedom. Addressing and researching this issue will uphold that the fundamental right for everyone from discrimination. In general, reading this report will make you informed on the relationships between people and law enforcement and see the causes that could lead to police violence. Which ultimatetly, will help create a more safer knowledgeable community.
